apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: webhooks
  newName: jackhoman/webhooks
  newTag: latest

resources:
- deployment.yaml
- service.yaml
- rbac.yaml

namespace: webhooks-system